server/apps/main/urls.py
from django.urls import path
from server.apps.main.views import search_git_data, git_result

app_name = 'main'

urlpatterns = [
    path('', search_git_data, name='search'),
    path('refresh', git_result, name='result'),
]

server/urls.py
"""
Main URL mapping configuration file.

Include other URLConfs from external apps using method `include()`.

It is also a good practice to keep a single URL to the root index page.

This examples uses Django's default media
files serving technique in development.
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.admindocs import urls as admindocs_urls
from django.urls import include, path
from django.views.generic import TemplateView
from health_check import urls as health_urls

from server.apps.main import urls as main_urls
from server.apps.main.views import index

admin.autodiscover()

urlpatterns = [
    # Apps:
    path('result/', include(main_urls, namespace='result')),

    # Health checks:
    path('health/', include(health_urls)),  # noqa: DJ05

    # django-admin:
    path('admin/doc/', include(admindocs_urls)),  # noqa: DJ05
    path('admin/', admin.site.urls),

    # It is a good practice to have explicit index view:
    path('', index, name='index'),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar  # noqa: WPS433
    from django.conf.urls.static import static  # noqa: WPS433

    urlpatterns = [
        # URLs specific only to django-debug-toolbar:
        path('__debug__/', include(debug_toolbar.urls)),  # noqa: DJ05
    ] + urlpatterns + static(  # type: ignore
        # Serving media files in development only:
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

server/apps/main/models.py
from django.db import models
from typing import final


@final
class Task_ID(models.Model):

    task_id = models.CharField(max_length=100)

    class Meta():
        verbose_name = 'Task_id'
        verbose_name_plural = 'Task_ids'

    def __str__(self) -> str:
        return '<Task_id {0}>'.format(self.task_id)

server/apps/main/forms.py
from django import forms


class SearchForm(forms.Form):

    git_nickname = forms.CharField(max_length=50,
                                   label='Search by author name',
                                   required=True
                                   )

server/apps/main/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, reverse
from server.apps.main.tasks import github_result
from server.apps.main.forms import SearchForm
from django.views.decorators.http import require_http_methods
from django.conf import settings
from celery.result import AsyncResult
from server.apps.main.models import Task_ID


@require_http_methods(['GET'])
def index(request: HttpRequest) -> HttpResponse:

    return render(request, 'index.html', {'form': SearchForm, })


@require_http_methods(['GET'])
def git_result(request: HttpRequest) -> HttpResponse:

    message = ''
    task_id = Task_ID.objects.last().task_id
    data = AsyncResult(task_id)
    if data.ready():
        result = data.get()

    return render(request, 'result.html', {'data': result,
                                           'message': message})


def search_git_data(request: HttpRequest) -> HttpResponse:

    message = ''

    if request.method == 'POST':

        name = request.POST.get('git_nickname')
        url = settings.GIT_API_URL + str(name) + '/repos?per_page=1000&page=1'

        message = "results not ready please wait"
        result = github_result.delay(url)
        task_id = result.task_id
        Task_ID.objects.create(task_id=task_id)

    return render(request, 'result.html', {'data': result,
                                           'message': message})

server/templates/index.html
<div  style="padding:40px;margin:40px;border:2px solid;align-items: center; #ccc" >
  <body>
      <!--[if lte IE 9]>
          <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
      <![endif]-->

      <a href="/admin">ADMIN</a>

  <div>
    <form method="POST" action="{% url 'main:search' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Search</button>
    </form>
  </div>

  </body>
  </div>

  </body>

server/templates/result.html
<div  style="padding:40px;margin:40px;border:2px solid;align-items: center; #ccc" >
  <body>
      <!--[if lte IE 9]>
          <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
      <![endif]-->
  <div>
    <form method="GET" action="{% url 'main:result' %}">
    {% csrf_token %}
    <button type="submit">REFRESH</button>
    </form>
  </div>
      {{ message }}
      {% for repo_name, stars_count in data.items %}
      <br>
      {{ repo_name }} {{ stars_count }}
      {% endfor %}
  </body>
  </div>

  </body>